# Generated by Django 4.2.3 on 2025-09-13 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title for the resume', max_length=200)),
                ('file', models.FileField(help_text='The resume file', upload_to='resumes/')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default resume for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this resume was uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this resume was last updated')),
                ('user', models.ForeignKey(help_text='User who owns this resume', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the company', max_length=200)),
                ('position', models.CharField(help_text='Job title or position name', max_length=200)),
                ('job_url', models.URLField(blank=True, help_text='URL to the job posting', null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='applied', help_text='Current status of the application', max_length=20)),
                ('applied_date', models.DateField(help_text='Date when the application was submitted')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the application', null=True)),
                ('salary_range', models.CharField(blank=True, help_text='Salary range if available', max_length=100, null=True)),
                ('location', models.CharField(blank=True, help_text='Job location', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('user', models.ForeignKey(help_text='User who submitted this application', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_date'],
                'unique_together': {('user', 'company_name', 'position')},
            },
        ),
    ]
