# Generated by Django 4.2.3 on 2025-09-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('institution', 'degree', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('company', 'position', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'start_date')},
        ),
        migrations.RemoveField(
            model_name='education',
            name='resume_template',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='resume_template',
        ),
        migrations.RemoveField(
            model_name='project',
            name='resume_template',
        ),
    ]
