# Generated by Django 5.2.6 on 2025-09-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="job_application",
            field=models.ForeignKey(
                blank=True,
                help_text="Job application related to this notification",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="job_tracker.jobapplication",
            ),
        ),
    ]
