# Generated by Django 5.2.6 on 2025-09-14 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('institution', 'degree', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('company', 'position', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'start_date')},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='meeting_minutes',
            field=models.TextField(blank=True, help_text='Meeting notes or interview minutes related to this job', null=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='custom_markdown',
            field=models.TextField(blank=True, help_text='Custom resume markdown (user-edited version)', null=True),
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content of the meeting note')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this meeting note was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this meeting note was last updated')),
                ('job_application', models.ForeignKey(help_text='Job application related to this meeting note', on_delete=django.db.models.deletion.CASCADE, to='job_tracker.jobapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='education',
            name='resume_template',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='resume_template',
        ),
        migrations.RemoveField(
            model_name='project',
            name='resume_template',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('show_date', models.DateTimeField(help_text='When to show this notification')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this notification is still active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this notification was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this notification was last updated')),
                ('job_application', models.ForeignKey(help_text='Job application related to this notification', on_delete=django.db.models.deletion.CASCADE, to='job_tracker.jobapplication')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'job_application', 'title')},
            },
        ),
    ]
