# Generated by Django 5.2.6 on 2025-09-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='meeting_minutes',
            field=models.TextField(blank=True, help_text='Meeting notes or interview minutes related to this job', null=True),
        ),
    ]
