# Generated by Django 5.2.6 on 2025-09-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_description',
            field=models.TextField(blank=True, help_text='Full job description for match analysis', null=True),
        ),
    ]
