# Generated by Django 5.2.6 on 2025-09-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='accepted_date',
            field=models.DateField(blank=True, help_text='Date when status changed to accepted', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateField(blank=True, help_text='Date when status changed to interview', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='rejected_date',
            field=models.DateField(blank=True, help_text='Date when status changed to rejected', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='withdrawn_date',
            field=models.DateField(blank=True, help_text='Date when status changed to withdrawn', null=True),
        ),
    ]
