# Generated by Django 4.2.3 on 2025-09-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0002_alter_education_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='custom_markdown',
            field=models.TextField(blank=True, help_text='Custom resume markdown (user-edited version)', null=True),
        ),
    ]
