# Generated by Django 5.2.6 on 2025-09-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0002_jobapplication_accepted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='accepted_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when status changed to accepted', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when status changed to interview', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='rejected_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when status changed to rejected', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='withdrawn_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when status changed to withdrawn', null=True),
        ),
    ]
