# Generated by Django 5.2.6 on 2025-09-13 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0002_jobapplication_meeting_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content of the meeting note')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this meeting note was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this meeting note was last updated')),
                ('job_application', models.ForeignKey(help_text='Job application related to this meeting note', on_delete=django.db.models.deletion.CASCADE, to='job_tracker.jobapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
