# Generated by Django 5.2.6 on 2025-09-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0002_jobapplication_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_description',
        ),
    ]
