# Generated by Django 5.2.6 on 2025-09-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0002_alter_notification_job_application'),
        ('job_tracker', '0003_alter_jobapplication_accepted_date_and_more'),
    ]

    operations = [
    ]
