# Generated by Django 4.2.3 on 2025-09-13 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_tracker', '0003_meetingnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('notification_type', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], default='immediate', help_text='Type of notification', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When to show this notification (for scheduled notifications)', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this notification is still active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this notification was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this notification was last updated')),
                ('job_application', models.ForeignKey(help_text='Job application related to this notification', on_delete=django.db.models.deletion.CASCADE, to='job_tracker.jobapplication')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'job_application', 'title')},
            },
        ),
    ]
