# Generated by Django 4.2.3 on 2025-09-13 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='scheduled_for',
        ),
        migrations.AddField(
            model_name='notification',
            name='show_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When to show this notification'),
            preserve_default=False,
        ),
    ]
