# Generated by Django 5.2.6 on 2025-09-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0003_resumetemplate_custom_markdown'),
        ('job_tracker', '0005_remove_notification_notification_type_and_more'),
    ]

    operations = [
    ]
